### ISSUE TITLE
getgrnam("root ")  failed

### ISSUE THREAD

**Issue by chamsiin1982** [Terry-Mao/MySQL-Syncer#10]
修改 master.cf 中
# execute user group

user terry terry
为
user root root

启动就报 getgrnam("root ")  failed  跟用户名有关？

**Comment by chamsiin1982** [comment]
找到原因了： 这句没执行 [root@TEST ~]# echo /usr/local/lib > /etc/ld.so.conf.d/redis.conf

**Comment by Terry-Mao** [comment]
:+1:
