### ISSUE TITLE
第一次全量导入redis

### ISSUE THREAD

**Issue by vebdhuz** [Terry-Mao/MySQL-Syncer#17]
有全量把数据和结构从msyql导入redis的功能不
或者有没有别的方法，在第一次的时候全量导入redis，之后就syncer来同步

**Comment by xushan** [comment]
全量导入可以用脚本实现啊，类似：mysql -h127.0.0.1 -uroot -p password -Ddatabase --skip-column-names --raw < ******.sql | redis-cli -h IP -p port –pipe
