### ISSUE TITLE
启动时执行./rs.sh slave start 失败

### ISSUE THREAD

**Issue by lanbaibai** [Terry-Mao/MySQL-Syncer#2]
我的操作系统 Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64) ，是台虚拟机。
Mysql是二进制安装5.5.16版本，
 MySQL-Syncer的安装目录是/data/tool/MySQL-Syncer-master
执行./rs.sh master start 成功
执行./rs.sh slave start 失败
错误提示./rs.sh: line 23: /data/tool/MySQL-Syncer-master/objs/rs_slave: No such file or directory
在objs目录中，我只找到rs_master这个文件，没找到rs_slave，如何解决？

**Comment by lanbaibai** [comment]
我执行了make slave_64解决了上述问题，
但是执行./rs.sh slave start 还是失败
在/tmp/rs_slave.log报下面错误
[ERROR] <thread : 140587381905152> rs_read()  failed, error or empty

**Comment by Terry-Mao** [comment]
贴下你的配置文件给我看下

**Comment by lanbaibai** [comment]
邮件发给你了。

**Comment by lanbaibai** [comment]
lanbaibai

发件人： Terry.Mao
发送时间： 2013-03-14 13:17
收件人： Terry-Mao/MySQL-Syncer
抄送： lanbaibai
主题： Re: [MySQL-Syncer] 启动时执行./rs.sh slave start 失败 (#2)
贴下你的配置文件给我看下

**Comment by Terry-Mao** [comment]
好像没收到，加我QQ：83873308

**Comment by Terry-Mao** [comment]
配置文件干掉\n
