### ISSUE TITLE
接收不到 master 的数据

### ISSUE THREAD

**Issue by phoenixluo** [Terry-Mao/MySQL-Syncer#3]
slave 日志显示在不停地 retry connect to master
master 日志显示 get dumpcmd failed

slave 程序在  rs_io_thread.c

 78             if(rs_recv_tmpbuf(si->recv_buf, si->svr_fd, &pack_len, 4) != RS_OK) {
 79                 goto retry;
 80             }

收不到数据。
我的 slave 配置文件：
[core]
# this is a master config file

# user group
user root root

# pid
pid /tmp/rs_slave.pid

# daemon
daemon 1

# log path
log /tmp/rs_slave.log

# log debug level (3 DEBUG : 2, INFO : 1, ERR : 0)
log.level 3

# debug level
debug.level BINLOG|ALLOC

[slave]
# listen addr
listen.addr 127.0.0.1

# listen port
listen.port 1919

# slave.info path
slave.info /home/server/MySQL-Syncer/etc/slave.info

# redis addr
redis.addr 127.0.0.1

# redis port
redis.port 6379

# slab init size
pool.initsize 100

# slab max memory size (10MB)
pool.memsize 10485760

# slab slab class grow factor
pool.factor 1.5

# ring buffer num
ringbuf.num 10000

# binlog save
binlog.save 10

# binlog savesec
binlog.savesec 30

# filter tables
filter.tables test.test

# recv buffer length
recvbuf.size 10485760

# server ring buffer empty sleep usec
svr.ringbuf.esusec 10000

# client ring buffer empty sleep usec
cli.ringbuf.esusec 10000

slave.info 文件
/var/log/mysql/mysql-bin.000001,287

master 配置文件

[core]
# this is a master config file

# execute user group
user server server

# pid file
pid /tmp/rs_master.pid

# daemon
daemon 1

# log path
log /tmp/rs_master.log

# log error level (3 DEBUG : 2 INFO : 1 ERR : 0)
log.level 3

# log debug level (CORE|ALLOC)
debug.level BINLOG

[master]

# listen addr
listen.addr 127.0.0.1

# listen port
listen.port 1919

# binlog index path
binlog.index /var/log/mysql/mysql-bin.index

# pool init size
pool.initsize 100

# pool max memory size (10MB)
pool.memsize 10485760

# pool slab class grow factor
pool.factor 1.5

# ring buffer num
ringbuf.num 8000

# send buf size
sendbuf.size 1024000

# io buf size (128MB)
iobuf.size 10485760
#iobuf.size 1024000

# current mysql server_id
server.id 123

# max dump thread
dump.thread 36

请问这是哪里出问题了？

**Comment by Terry-Mao** [comment]
slave.info 文件结尾有无空格？

**Comment by Terry-Mao** [comment]
echo -n "binlog_path,pos" > slave.info 这样才不会有空格

**Comment by phoenixluo** [comment]
是 slave.info 的问题，把空格去掉就好了。
