### ISSUE TITLE
2014-03-05 15:39:04 [ERROR] <thread : 47661750942016> get dumpcmd failed

### ISSUE THREAD

**Issue by h3110w0r1d** [Terry-Mao/MySQL-Syncer#6]
2014-03-05 15:39:04 [ERROR] <thread : 47661750942016> get dumpcmd failed

这个是什么问题呢?

**Comment by Terry-Mao** [comment]
指令错误，一般是配置文件错误了

**Comment by h3110w0r1d** [comment]
slave.info的空格问题，前面有人也有这问题，关了把

**Comment by Terry-Mao** [comment]
这个坑很容易踩，以后搞个简单的方式好了。。。有什么问题加QQ：83873308
